/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.presentacion;

import itson.control.ControlActualizarPerfil;
import itson.control.ControlComprarBoleto;
import itson.control.ControlIniciarSesion;
import itson.control.ControlRegistrarDeposito;
import itson.control.ControlVenderBoletos;
import itson.entidades.Usuario;
import itson.persistencia.BoletosDAO;
import itson.persistencia.DepositosDAO;
import itson.persistencia.ManejadorConexiones;
import itson.persistencia.UsuariosDAO;
import itson.usuariosDTOs.SesionDTO;
import observador.Observer;

/**
 *
 * @author rauln
 */
public class Menu extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Menu
     */
    ManejadorConexiones manejadorConexiones = new ManejadorConexiones();
    UsuariosDAO usuariosDAO = new UsuariosDAO(manejadorConexiones);
    BoletosDAO boletosDAO = new BoletosDAO(manejadorConexiones);
    DepositosDAO depositosDAO = new DepositosDAO(manejadorConexiones);
    ControlIniciarSesion controlInicio = new ControlIniciarSesion(usuariosDAO);
    ControlComprarBoleto controlActualizar = new ControlComprarBoleto(boletosDAO);
    ControlRegistrarDeposito controlDeposito = new ControlRegistrarDeposito(depositosDAO);
    ControlVenderBoletos controlVenderBoletos = new ControlVenderBoletos(boletosDAO);
    ControlActualizarPerfil controlActualizarPerfil = new ControlActualizarPerfil(usuariosDAO);

    public Menu() {
        initComponents();
        // Suscribirse a los cambios en SesionDTO
        SesionDTO.getInstancia().agregarObservador(this);
        actualizarLabels();
    }

    // Método de la interfaz Observer
    @Override
    public void actualizar() {
        actualizarLabels();
    }

    private void actualizarLabels() {
        Usuario usuario = SesionDTO.getInstancia().getUsuarioActual();
        if (usuario != null) {
            saldoLabel.setText("Saldo: $" + usuario.getSaldo());
            usuarioLabel.setText(usuario.getNombre());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        venderBoletosLabel = new javax.swing.JLabel();
        misBoletosLabel = new javax.swing.JLabel();
        cerrarSesionLabel = new javax.swing.JLabel();
        boletosApartadosLabel = new javax.swing.JLabel();
        transaccionesLabel = new javax.swing.JLabel();
        comprarBoletosLabel = new javax.swing.JLabel();
        botonAgregarSaldo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        usuarioLabel = new javax.swing.JLabel();
        saludoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("SIGN UP");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("menuFrame"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(0, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("MENU");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        venderBoletosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VenderBoletos.png"))); // NOI18N
        venderBoletosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venderBoletosLabelMouseClicked(evt);
            }
        });

        misBoletosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisBoletos.png"))); // NOI18N
        misBoletosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                misBoletosLabelMouseClicked(evt);
            }
        });

        cerrarSesionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CerrarSesion.png"))); // NOI18N
        cerrarSesionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionLabelMouseClicked(evt);
            }
        });

        boletosApartadosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BoletosApartados.png"))); // NOI18N
        boletosApartadosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boletosApartadosLabelMouseClicked(evt);
            }
        });

        transaccionesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HistorialTransacciones.png"))); // NOI18N
        transaccionesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaccionesLabelMouseClicked(evt);
            }
        });

        comprarBoletosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComprarBoletos.png"))); // NOI18N
        comprarBoletosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprarBoletosLabelMouseClicked(evt);
            }
        });

        botonAgregarSaldo.setBackground(new java.awt.Color(153, 255, 153));
        botonAgregarSaldo.setText("Agregar saldo");
        botonAgregarSaldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAgregarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarSaldoActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar perfil");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAgregarSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cerrarSesionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(boletosApartadosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(misBoletosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(comprarBoletosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transaccionesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(venderBoletosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAgregarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(venderBoletosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(misBoletosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comprarBoletosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boletosApartadosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrarSesionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transaccionesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        usuarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(0, 102, 102));

        saludoLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        saludoLabel.setText("Bienvenido,");

        jLabel1.setText("SALDO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saludoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saldoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saludoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarBoletosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprarBoletosLabelMouseClicked
        // TODO add your handling code here:
        ComprarBoletos comprarBoletos = new ComprarBoletos(controlActualizar);
        comprarBoletos.setVisible(true);
        comprarBoletos.pack();
        comprarBoletos.setLocationRelativeTo(null);
        //this.setVisible(false);

    }//GEN-LAST:event_comprarBoletosLabelMouseClicked

    private void misBoletosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_misBoletosLabelMouseClicked
        // TODO add your handling code here:
        MisBoletos misBoletos = new MisBoletos();
        misBoletos.setVisible(true);
        misBoletos.pack();
        misBoletos.setLocationRelativeTo(null);
        //this.setVisible(false);
    }//GEN-LAST:event_misBoletosLabelMouseClicked

    private void venderBoletosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venderBoletosLabelMouseClicked
        // TODO add your handling code here:
        VenderBoletos venderBoletos = new VenderBoletos(controlVenderBoletos);
        venderBoletos.setVisible(true);
        venderBoletos.pack();
        venderBoletos.setLocationRelativeTo(null);
        //this.setVisible(false);
    }//GEN-LAST:event_venderBoletosLabelMouseClicked

    private void cerrarSesionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        //this.setVisible(false);
    }//GEN-LAST:event_cerrarSesionLabelMouseClicked

    private void boletosApartadosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boletosApartadosLabelMouseClicked
        // TODO add your handling code here:
        BoletosApartados boletosApartados = new BoletosApartados();
        boletosApartados.setVisible(true);
        boletosApartados.pack();
        boletosApartados.setLocationRelativeTo(null);
        //this.setVisible(false);
    }//GEN-LAST:event_boletosApartadosLabelMouseClicked

    private void transaccionesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaccionesLabelMouseClicked
        // TODO add your handling code here:
        HistorialTransacciones historialTransacciones = new HistorialTransacciones();
        historialTransacciones.setVisible(true);
        historialTransacciones.pack();
        historialTransacciones.setLocationRelativeTo(null);
        //this.setVisible(false);
    }//GEN-LAST:event_transaccionesLabelMouseClicked

    private void botonAgregarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarSaldoActionPerformed
        controlDeposito.iniciarFlujo();
    }//GEN-LAST:event_botonAgregarSaldoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.controlActualizarPerfil.inciarFlujo();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boletosApartadosLabel;
    private javax.swing.JButton botonAgregarSaldo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel cerrarSesionLabel;
    private javax.swing.JLabel comprarBoletosLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel misBoletosLabel;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JLabel saludoLabel;
    private javax.swing.JLabel transaccionesLabel;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JLabel venderBoletosLabel;
    // End of variables declaration//GEN-END:variables
}
