/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.presentacion;

import itson.control.ControlComprarBoleto;
import itson.control.ControlIniciarSesion;
import itson.control.ControlVenderBoletos;
import itson.entidades.Usuario;
import itson.usuariosDTOs.SesionDTO;
import observador.Observer;

/**
 *
 * @author rauln
 */
public class VenderBoletos extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form VenderBoletos
     */
   
    private final ControlVenderBoletos controlVenderBoletos;

    public VenderBoletos(ControlVenderBoletos controlVenderBoletos) {
        initComponents();
        this.controlVenderBoletos = controlVenderBoletos;

        // Quitar el borde del JDesktopPane y poner fondo blanco
        campoTabla.setBorder(null);
        campoTabla.setOpaque(true);
        campoTabla.setBackground(new java.awt.Color(255, 255, 255));
        
        // Crear la instancia de TablaVenderBoletos
        TablaVenderBoletos tablaVenderBoletos = new TablaVenderBoletos(controlVenderBoletos);

        // Deshabilitar todas las opciones de redimensionamiento y movimiento
        tablaVenderBoletos.setClosable(false);  // No se puede cerrar
        tablaVenderBoletos.setResizable(false); // No se puede redimensionar
        tablaVenderBoletos.setMaximizable(false); // No se puede maximizar
        tablaVenderBoletos.setIconifiable(false); // No se puede minimizar
        tablaVenderBoletos.setTitle(null); // Sin título en el borde superior

        // Quitar el borde superior para evitar que se arrastre
        ((javax.swing.plaf.basic.BasicInternalFrameUI) tablaVenderBoletos.getUI()).setNorthPane(null);

        // Fijar el tamaño y posición dentro del JDesktopPane
        tablaVenderBoletos.setBounds(0, 0, 700, 300); // Tamaño fijo (ancho x alto)

        // Añadir y hacer visible
        campoTabla.add(tablaVenderBoletos);
        tablaVenderBoletos.setVisible(true);

        // Actualizar el panel
        actualizar();
        campoTabla.revalidate();
        campoTabla.repaint();
    }
    
    @Override
    public void actualizar() {
        actualizarLabels();
    }

    private void actualizarLabels() {
        Usuario usuario = SesionDTO.getInstancia().getUsuarioActual();
        if (usuario != null) {
            nombreLabel.setText("Hola! "+usuario.getNombre());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoTabla = new javax.swing.JDesktopPane();
        nombreLabel = new javax.swing.JLabel();
        nombreLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombreLabel2 = new javax.swing.JLabel();
        nomrbreLabel = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuarioIcon.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuarioIcon.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuarioIcon.png"))); // NOI18N

        campoTabla.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout campoTablaLayout = new javax.swing.GroupLayout(campoTabla);
        campoTabla.setLayout(campoTablaLayout);
        campoTablaLayout.setHorizontalGroup(
            campoTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        campoTablaLayout.setVerticalGroup(
            campoTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        nombreLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        nombreLabel.setText("Hola!");

        nombreLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Vende tus boletos aqui!");

        nombreLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N

        nomrbreLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(campoTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreLabel)
                        .addGap(89, 89, 89)
                        .addComponent(nombreLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nomrbreLabel))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nombreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nomrbreLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(campoTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane campoTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JLabel nombreLabel2;
    private javax.swing.JLabel nomrbreLabel;
    // End of variables declaration//GEN-END:variables
}
